gantt
	title 芝山PJ工程表
	axisFormat %m/%d
	section ネイティブコードバックエンド
		コード生成ライブラリの実装: done, 2023-07-01, 5d
		トランスパイラの実装(言語コア部分): done, 2023-07-05, 26d
		トランスパイラの実装(Python API部分): active, 2023-08-01, 200d
	section パッケージマネージャ
		設計: done, 2023-07-06, 1d
		基本コマンドの実装: done, 2023-07-06, 11d
		アップローダの実装: done, 2023-08-01, 10d
		ダウンローダの実装: done, 2023-09-01, 48d
	section コンパイラのバグ修正
		コード生成バグ: done, 2023-08-17, 3d
		並列コンパイルバグ: done, 2023-07-15, 90d
	section Pythonパッケージの型付け
		torchの型付け: active, 2023-12-01, 50d
